#ifndef TODOLIST_VERSION_H
#define TODOLIST_VERSION_H

#define TODOLIST_VERSION_MAJOR 1
#define TODOLIST_VERSION_MINOR 0
#define TODOLIST_VERSION_PATCH 0

#define TODOLIST_VERSION "1.0.0"

#endif // TODOLIST_VERSION_H
